service: music-suggestion

provider:
  name: aws
  runtime: java11
  profile: serverless-music-suggestion
  region: eu-west-1

package:
  artifact: target/scala-2.13/music-suggestion.jar

functions:
  greetings:
    handler: es.eriktorr.music.greetings.GuestGreeterProxy2
    environment:
      spotifyClientId: ${env:spotifyClientId}
      spotifyClientSecret: ${env:spotifyClientSecret}
    events:
      - http:
          path: greet
          method: get
      - http:
          path: greet/{name}
          method: get
          request:
            parameters:
              paths:
                name: true
