service: music-suggestion

provider:
  name: aws
  runtime: java11
  profile: serverless-music-suggestion
  region: eu-west-1

package:
  artifact: target/scala-2.13/music-suggestion.jar

functions:
  hello:
    handler: es.eriktorr.music.MainApiGatewayProxyHandler
    events:
      - http:
          path: greet/guest
          method: get
